version: 2

builds:
  - id: linux
    main: ./main.go
    goos: [linux]
    goarch: [amd64]
    dir: .
    binary: slurm_exporter
    ldflags:
      - -X main.version={{.Version}}
    flags: ["-v"]

archives:
  - id: default
    builds: [linux]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - config.yml
      - bin/**
    wrap_in_directory: true

release:
  github:
    owner: "MA-DOS"
    name: "SlurmExporter"

checksum:
  name_template: "checksums.txt"

git:
  tag_sort: semver