name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run semantic-release
        id: semrel
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch and hard-reset to latest tag
        run: |
          git fetch --tags --force
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "RELEASE_TAG=$LATEST_TAG" >> $GITHUB_ENV
          git reset --hard "$LATEST_TAG"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.18"

      - name: Install GoReleaser
        run: |
          curl -sSfL https://github.com/goreleaser/goreleaser/releases/download/v2.9.0/goreleaser_Linux_x86_64.tar.gz | tar -xz
          sudo mv goreleaser /usr/local/bin/

      - name: Run GoReleaser with the tag
        run: |
          echo "Using tag: $RELEASE_TAG"
          goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}